language: python
python:
 - '3.8'

before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - pipenv install

services:
 - postgresql

env: DJANGO_SETTINGS_MODULE=settings.travis_settings

script: 
 - python manage.py migrate frontpage
 - python manage.py test tests.unit
 - python manage.py test tests.integration