language: python
python:
 - '3.8'

before_script:
 - pipenv install

services:
 - postgresql

env: DJANGO_SETTINGS_MODULE=settings.travis_settings

script: 
 - python manage.py test tests.unit --settings=settings.travis_settings --keeepdb
 - python manage.py test tests.integration --settings=settings.travis_settings --keeepdb