# Generated by Django 3.0.8 on 2020-08-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_access_admin', '0002_auto_20200811_1046'),
        ('frontpage', '0002_auto_20200730_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='Contenu texte')),
                ('img_url', models.ImageField(upload_to='news_img', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Child_care_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la structure')),
                ('max_child_number', models.IntegerField(verbose_name='Places maximum')),
                ('type_of_facility', models.CharField(choices=[('MC', 'Micro-Crèche'), ('C', 'Crèche'), ('MAM', 'MAM'), ('MC', 'Crèche-Parentale'), ('MC', 'Crèche-Municipale'), ('MC', "Crèche d'entreprise"), ('MC', 'Crèche associative')], max_length=50, verbose_name='Type de structure')),
                ('status', models.CharField(choices=[('A', 'Active'), ('NA', 'Non Active'), ('EC', 'En cours de création')], max_length=50, verbose_name='Statut')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_access_admin.Address')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.New')),
            ],
        ),
    ]
