# Generated by Django 3.0.8 on 2020-08-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_child_care_facility_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child_care_facility',
            name='new',
        ),
        migrations.AddField(
            model_name='new',
            name='cc_facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontpage.Child_care_facility'),
            preserve_default=False,
        ),
    ]
