# Generated by Django 3.0.8 on 2020-08-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_auto_20200811_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
