# Generated by Django 3.0.8 on 2020-08-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child_care_facility',
            options={'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Nouvelle', 'verbose_name_plural': 'Nouvelles'},
        ),
    ]
