# Generated by Django 3.0.8 on 2020-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20200811_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_care_facility',
            name='email',
            field=models.EmailField(default='mam@lebugue.fr', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child_care_facility',
            name='phone',
            field=models.CharField(default=112233445566, max_length=14, verbose_name='Téléphone'),
            preserve_default=False,
        ),
    ]
