# Generated by Django 3.1 on 2020-08-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_access_admin', '0008_auto_20200831_1059'),
        ('frontpage', '0010_auto_20200820_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_care_facility',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_access_admin.address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='child_care_facility',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse Email'),
        ),
    ]
