# Generated by Django 3.0.8 on 2020-08-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_auto_20200820_1152'),
        ('day_to_day', '0002_auto_20200820_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Contenu')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('cc_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.Child_care_facility', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'Message de la Direction',
                'verbose_name_plural': 'Messages de la Direction',
            },
        ),
    ]
