# Generated by Django 3.0.8 on 2020-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_day', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='', max_length=200, verbose_name='Contenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titre'),
        ),
    ]
