# Generated by Django 3.0.8 on 2020-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_day', '0005_auto_20200820_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfact',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='Commentaire général'),
        ),
    ]
