# Generated by Django 3.1 on 2020-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_access_admin', '0008_auto_20200831_1059'),
        ('day_to_day', '0010_auto_20200826_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='relative',
            field=models.ManyToManyField(through='day_to_day.Family_link', to='auth_access_admin.FamilyMember', verbose_name='Liens Familiaux'),
        ),
    ]
