# Generated by Django 3.1 on 2020-09-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_day', '0011_auto_20200901_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalevent',
            old_name='body_temp_deg_C',
            new_name='temperature',
        ),
    ]
