# Generated by Django 3.1 on 2020-09-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_day', '0012_auto_20200901_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalevent',
            old_name='temperature',
            new_name='body_temp_deg_C',
        ),
    ]
