# Generated by Django 3.1 on 2020-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_day', '0013_auto_20200901_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalevent',
            name='given_paracetamol_qtty_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Paracétamol donné en mg'),
        ),
    ]
