# Generated by Django 3.1.1 on 2020-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_day', '0014_auto_20200901_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalevent',
            name='paracetamol_given_time',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'administration"),
        ),
    ]
