# Generated by Django 3.0.8 on 2020-08-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth_access_admin', '0002_auto_20200811_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
