# Generated by Django 3.0.8 on 2020-08-11 10:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20200811_1219'),
        ('auth_access_admin', '0003_auto_20200811_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=14, verbose_name="Téléphone d'urgence")),
                ('IdScan', models.ImageField(upload_to='ids', verbose_name="Pièce d'identité")),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_access_admin.Address')),
            ],
            options={
                'verbose_name': 'Membre Famille',
                'verbose_name_plural': 'Membres Famille',
            },
            bases=('frontpage.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=14, verbose_name="Téléphone d'urgence")),
                ('IdScan', models.ImageField(upload_to='ids', verbose_name="Pièce d'identité")),
                ('occupation', models.CharField(max_length=100, verbose_name='Métier')),
                ('employee_nr', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name="Numéro d'employé")),
                ('diploma', models.CharField(max_length=100, verbose_name='Plus haut diplôme obtenu')),
                ('Is_manager', models.BooleanField(verbose_name='Direction')),
                ('employee_contract', models.ImageField(upload_to='e_contracts', verbose_name='Scanner du contrat de travail')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_access_admin.Address')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
            bases=('frontpage.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
