# Generated by Django 3.0.8 on 2020-08-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_access_admin', '0005_auto_20200820_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_access_admin.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_access_admin.Address', verbose_name='Adresse'),
        ),
    ]
