# Generated by Django 3.0.8 on 2020-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_access_admin', '0006_auto_20200820_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='has_daylyfact_access',
            field=models.BooleanField(default=False, verbose_name='Accès aux transmissions'),
        ),
    ]
