# Generated by Django 3.1 on 2020-08-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_access_admin', '0007_familymember_has_daylyfact_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='Compléments'),
        ),
    ]
