# Generated by Django 3.1.1 on 2020-09-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0011_auto_20200831_1119'),
        ('auth_access_admin', '0008_auto_20200831_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cc_facility',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='frontpage.child_care_facility', verbose_name='Structure'),
            preserve_default=False,
        ),
    ]
