# Generated by Django 3.1.1 on 2020-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_access_admin', '0009_employee_cc_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Is_manager',
            field=models.BooleanField(default=False, verbose_name='Direction'),
        ),
    ]
